name: Train and Deploy Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Train model
        run: npm run start

      - name: Push model.json to rfahmi/elsa repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main-test
          repository: rfahmi/elsa
          directory: ./config
          force: true
        env:
          GITHUB_USER_NAME: rfahmi
          GITHUB_USER_EMAIL: hello@rfahmi.com
          COMMIT_MESSAGE: "Update model.json"
          FILE_PATTERN: "./model.json"
